Repository Team-Plu/Plu-iOS, pull requests merged in 2023-12, with the labels that each got.

#3 [SETTING] 폰트 추가(#2)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Font/Font.swift
  Plu-iOS/Plu-iOS/Font/SUITE-Bold.ttf
  Plu-iOS/Plu-iOS/Font/SUITE-Medium.ttf
  Plu-iOS/Plu-iOS/Font/SUITE-Regular.ttf
  Plu-iOS/Plu-iOS/Font/SUITE-SemiBold.ttf
  Plu-iOS/Plu-iOS/Font/UIFont+.swift
  Plu-iOS/Plu-iOS/SceneDelegate.swift
  Plu-iOS/Plu-iOS/ViewController.swift
Labels: ⚙️ SETTING, 👨‍💻 의성

#14 [FEAT] TabBar Custom (#11)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/Font/Font.swift
  Plu-iOS/Plu-iOS/Global/Extention/CALayer+.swift
  Plu-iOS/Plu-iOS/Scenes/Tabbar/TabbarViewController.swift
Labels: 👩🏻‍💻 찬미, 🎨 UI

#12 [FEAT] MyPage UI구현(#9)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Application/SceneDelegate.swift
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Interface/Collections/CollectionViewCellRegisterDequeueProtocol.swift
  Plu-iOS/Plu-iOS/Interface/Collections/TableSectionViewRegisterDequeueProtocol.swift
  Plu-iOS/Plu-iOS/Interface/Collections/TableViewCellRegisterDequeueProtocol.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageAlarmTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageAppVersionTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageGeneralTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Enum/MyPageCellHeight.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Enum/MyPageSection.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Enum/MyPageSectionHeaderHeight.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MyPageAlarmCellData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MyPageUserData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageAppVersionCellData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageInfomationCellData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageUserExitCellData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/MyPageInerface/MyPageCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/MyPageViewController.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/SectionHeader/MyPageRoundSectionHeaderView.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/View/MyPageHeaderView.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/View/MyPageTableView.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/MyPageViewController.swift
Labels: 👨‍💻 의성, 🎨 UI

#13 [FEAT] 모두의 답변뷰 UI 구현 (#10)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUButton.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLULabel.swift
  Plu-iOS/Plu-iOS/Global/Enum/ElementColor.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/AnswerFilterButtonType.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/AnswerFilterMenuView.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/AnswerTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/AnswerView.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Dummy.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OtherAnswersDiffableModel.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OthersAnswerTableView.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OthersAnswerViewController.swift
Labels: 🧑🏻‍💻 민재, 🎨 UI

#23 [FEAT] 탈퇴 UI 구현
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ResignDescriptionView.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ResignViewController.swift
Labels: 🧑🏻‍💻 민재, 🎨 UI

#20 [FEAT] OnboardingUI및 로직구현(#17)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Application/SceneDelegate.swift
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/btn_erase.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/btn_erase.imageset/_btn_erase.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/ImageLiterals.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUExplanationView.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLULabel.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PluTextField.swift
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Global/Extention/UIEdgeInsets+.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MyPageAlarmCellData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageAppVersionCellData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageInfomationCellData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageUserExitCellData.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/MangerImpl/OnboardingManagerStub.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/Model/NicknameState.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/OnboardingInteface/NicknameCheck.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/OnboardingInteface/NicknameManager.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/OnboardingViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/PluTempButton.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewController/OnboardingViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewModel/OnboardingViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Tabbar/TabbarViewController.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/ImageDummy.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/TodayQuestionViewController.swift
Labels: 👨‍💻 의성, 🎨 UI, ✨FEAT

#18 [FEAT] 일기기록 UI 구현 (#15)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Enum/AnswerFilterButtonType.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Model/Dummy.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Model/OtherAnswersDiffableModel.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OthersAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/TableView/AnswerTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/TableView/OthersAnswerTableView.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/View/AnswerFilterMenuView.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/View/AnswerView.swift
  Plu-iOS/Plu-iOS/Scenes/Record/Model/RecordDiffableModel.swift
  Plu-iOS/Plu-iOS/Scenes/Record/Model/RecordDummy.swift
  Plu-iOS/Plu-iOS/Scenes/Record/RecordDiffableDataSource.swift
  Plu-iOS/Plu-iOS/Scenes/Record/RecordViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Record/TableViewCell/RecordQuestionTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/Record/View/QuestionView.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ResignDescriptionView.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ResignViewController.swift
Labels: 🧑🏻‍💻 민재, 🎨 UI

#26 [FEAT] 닉네임 수정하기 UI 구현
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUImageView.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PluTextField.swift
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/NicknameEditViewController.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/NicknameEditViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/MangerImpl/NicknameManagerStub.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/Model/NicknameState.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/OnboardingInteface/NicknameCheck.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewController/OnboardingViewController.swift
  Plu-iOS/Plu-iOS/Scenes/ProfileEdit/ProfileEditViewController.swift
Labels: 👨‍💻 의성, 🎨 UI, ✨FEAT

#28 [FEAT] 스플래시 UI 구현
  Plu-iOS/Plu-iOS/Application/SceneDelegate.swift
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Splash/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Splash/ic_eyes_air.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Splash/ic_eyes_air.imageset/ic_eyes_air.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Splash/ic_eyes_dust.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Splash/ic_eyes_dust.imageset/ic_eyes_dust.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Splash/ic_eyes_fire.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Splash/ic_eyes_fire.imageset/ic_eyes_fire.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Splash/ic_eyes_water.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Splash/ic_eyes_water.imageset/ic_eyes_water.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/ic_eyes.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/ic_eyes.imageset/ic_eyes.png
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/ic_eyes.imageset/ic_eyes@2x.png
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/ic_eyes.imageset/ic_eyes@3x.png
  Plu-iOS/Plu-iOS/DesignSystem/Image/ImageLiterals.swift
  Plu-iOS/Plu-iOS/Global/Enum/ElementColor.swift
  Plu-iOS/Plu-iOS/Scenes/Splash/SplashViewController.swift
Labels: 👨‍💻 의성, 🎨 UI

#29 [FEAT] 로그인(튜토리얼) UI 구현 (#25)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Login/screenshot1.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Login/screenshot1.imageset/screenshot1.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Login/screenshot2.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Login/screenshot2.imageset/screenshot2.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Login/screenshot3.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Login/screenshot3.imageset/screenshot3.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/ImageLiterals.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUButton.swift
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Global/Extention/se+.swift
  Plu-iOS/Plu-iOS/Scenes/Login/LoginModel.swift
  Plu-iOS/Plu-iOS/Scenes/Login/LoginViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Login/TutorialCollectionViewCell.swift
Labels: 🧑🏻‍💻 민재, 🎨 UI

#30 [FEAT] 나의 답변 작성 UI 구현 (#16)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/EverydayAnswerView.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUTextView.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUUnderLine.swift
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Scenes/MyAnswer/AnswerCautionView.swift
  Plu-iOS/Plu-iOS/Scenes/MyAnswer/KeyboardType.swift
  Plu-iOS/Plu-iOS/Scenes/MyAnswer/MyAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/MyAnswer/MyAnswerViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OthersAnswerViewController.swift
Labels: 👩🏻‍💻 찬미, 🎨 UI

#31 [FEAT] 나의 답변 상세 UI (#22)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUEverydayAnswerView.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/AnswerDetailViewController.swift
  Plu-iOS/Plu-iOS/Scenes/MyAnswer/MyAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OthersAnswerViewController.swift
Labels: 👩🏻‍💻 찬미, 🎨 UI, ✨FEAT

#34 [ADD] (임시UI)AlarmPopUp 구현(#32)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Application/SceneDelegate.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/AlarmPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/PopUpDimmedViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/RegisterPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/SelectMonthPopUpViewController.swift
Labels: ⚙️ SETTING, 👨‍💻 의성

#36 [FEAT] Coordinator 설계 (#33)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Application/SceneDelegate.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUButton.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AnswerDetailCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AppCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AuthCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyAnswerCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyPageCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/OtherAnswerCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/PopUpCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/RecordCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/SplashCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/TabBarCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/TodayQuestionCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/AnswerDetailCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/AuthCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/Coordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/MyAnswerCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/MyPageCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/OtherAnswersCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/PopUpCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/RecordCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/SplashCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/TabbarCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/TodayQuestionCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Login/LoginViewController.swift
  Plu-iOS/Plu-iOS/Scenes/MyAnswer/MyAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Enum/MyPageSection.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/View/MyPageTableView.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/MyPageViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewController/OnboardingViewController.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OthersAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/AlarmPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/RegisterPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/SelectMonthPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Record/RecordViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Splash/SplashViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Tabbar/TabbarViewController.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/TodayQuestionViewController.swift
Labels: 🧑🏻‍💻 민재, 👩🏻‍💻 찬미, 👨‍💻 의성, ✨FEAT

#37 [REFACTOR] 기존 Coordinator의 parent/child구조를 self-deallocation로 리팩터링(#35)
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AnswerDetailCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AppCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AuthCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyAnswerCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyPageCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/OtherAnswerCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/PopUpCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/RecordCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/SplashCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/TabBarCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/TodayQuestionCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/Coordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/MyPageCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Login/LoginViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Login/TutorialCollectionViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageAlarmTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageAppVersionTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageGeneralTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/View/MyPageHeaderView.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/View/MyPageTableView.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/MyPageViewController.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OthersAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/TableView/AnswerTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/View/AnswerView.swift
  Plu-iOS/Plu-iOS/Scenes/Record/RecordDiffableDataSource.swift
  Plu-iOS/Plu-iOS/Scenes/Record/TableViewCell/RecordQuestionTableViewCell.swift
Labels: 🧑🏻‍💻 민재, 👩🏻‍💻 찬미, 👨‍💻 의성, ♻️REFACTOR

#41 [FEAT] 1차 UI추가작업 (Custom NavigationBar) (#40)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/NicknameEditViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PLUNavigationBarView.swift
Labels: 🧑🏻‍💻 민재, 🎨 UI

#42 [FEAT] 1차UI추가작업(PopupUI수정)(#38)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/Image/ImageLiterals.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUButton.swift
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Global/Extention/UIButton+.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/PopUpCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/MyAnswer/MyAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/AlarmPopUp/AlarmPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/AlarmPopUp/AlarmPopUpViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/AlarmPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/PLUPopUpContainerView.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/PopUpDimmedViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/RegisterPopUp/RegisterPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/RegisterPopUp/RegisterPopUpViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/RegisterPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/SelectMonthPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/SelectYearAndMonthPopUp/SelectMonthPopUpViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/SelectYearAndMonthPopUp/SelectYearAndMonthPopUpViewController.swift
Labels: 👨‍💻 의성, 🎨 UI

#43 [FEAT] TodayQuestion VC 최초 진입시 알람 팝업 UserDefaults 데이터 로직 구현 (#39)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Global/Constant/UserDefaultKey.swift
  Plu-iOS/Plu-iOS/Global/UserDefault/UserDefaultsManager.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/TodayQuestionViewController.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/TodayQuestionViewModel.swift
Labels: 👩🏻‍💻 찬미, ✨FEAT

#50 [FEAT] UI 마무리 작업 (#45)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/ic_alarm.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/ic_alarm.imageset/ic_alarm.png
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/ic_alarm.imageset/ic_alarm.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/ic_alarm.imageset/ic_alarm@2x.png
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/ic_alarm.imageset/ic_alarm@3x.png
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/plu_wordmark_large.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/plu_wordmark_large.imageset/plu_wordmark_large.png
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/plu_wordmark_large.imageset/plu_wordmark_large.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/plu_wordmark_large.imageset/plu_wordmark_large@2x.png
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/plu_wordmark_large.imageset/plu_wordmark_large@3x.png
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUButton.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUIndicator.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PluTextField.swift
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Global/Extention/UIViewController+.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AppCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AuthCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyAnswerCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyPageCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/PopUpCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/TodayQuestionCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/Coordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/ExitUser.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/MyPageCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/PopUpCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageAlarmTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageAppVersionTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageGeneralTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Enum/MyPageInfomaitonType.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Enum/MyPageSection.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Enum/MyPageUserExitType.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MyPageAlarmData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageAppVersionData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageInfomationCellData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageUserExitCellData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/MyPageViewController.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/NicknameEditViewController.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/NicknameEditViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/MangerImpl/NicknameManagerStub.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/OnboardingInteface/NicknameManager.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewController/OnboardingViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewModel/OnboardingViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/PLUNavigationBarView.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/AlarmPopUp/AlarmPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/AlarmPopUp/AlarmPopUpViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ResignViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Splash/SplashViewController.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/TodayQuestionViewController.swift
Labels: 👨‍💻 의성, 🎨 UI

#53 [FIX] PLU 1차 UI 최종(#51)
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Login/ic_character_set.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Login/ic_character_set.imageset/ic_character_set.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Onboarding/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Onboarding/btn_erase.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Onboarding/btn_erase.imageset/_btn_erase.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/PopUp/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/PopUp/ic_alarm.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/PopUp/ic_alarm.imageset/ic_alarm.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Wordmark/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Wordmark/plu_wordmark_large.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Wordmark/plu_wordmark_large.imageset/plu_wordmark_large.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Wordmark/plu_wordmark_small.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Wordmark/plu_wordmark_small.imageset/plu_wordmark_small.png
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Wordmark/plu_wordmark_small.imageset/plu_wordmark_small@2x.png
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Wordmark/plu_wordmark_small.imageset/plu_wordmark_small@3x.png
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUButton.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/AnswerDetailViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Login/LoginViewController.swift
  Plu-iOS/Plu-iOS/Scenes/MyAnswer/MyAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/NicknameEditViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/RegisterPopUp/RegisterPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ResignViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Splash/SplashViewController.swift
Labels: 🧑🏻‍💻 민재, 👩🏻‍💻 찬미, 👨‍💻 의성, 🎨 UI

#61 [FEAT] OnboardingViewController MVVM-C(Combine) + Adaptor Pattern 적용
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Global/Protocol/ViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AuthCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/PopUpCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageAlarmTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/NicknameEditViewController.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/NicknameEditViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/Adaptor/OnboardingAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/Adaptor/OnboardingNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/MangerImpl/NicknameManagerStub.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/OnboardingInteface/NicknameCheck.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/OnboardingInteface/NicknameManager.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/PluTempButton.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewController/OnboardingViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewModel/OnboardingViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewModel/OnboardingViewModelImpl.swift
Labels: 👨‍💻 의성, ✨FEAT

#64 [FEAT] LoginViewController MVVM-C(Combine) + Adaptor Pattern 적용 (#56)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUButton.swift
  Plu-iOS/Plu-iOS/Global/Enum/LoadingState.swift
  Plu-iOS/Plu-iOS/Global/Protocol/ViewModel.swift
  Plu-iOS/Plu-iOS/Network/NetworkError.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AuthCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Adaptor/LoginAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Adaptor/LoginNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Manager/LoginManager.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Manager/LoginManagerImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Model/Login.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Model/LoginModel.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Model/LoginState.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Model/SocialLogin.swift
  Plu-iOS/Plu-iOS/Scenes/Login/View/TutorialCollectionViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/Login/ViewController/LoginViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Login/ViewModel/LoginViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Login/ViewModel/LoginViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/NicknameEditViewModel.swift
Labels: 🧑🏻‍💻 민재, ✨FEAT

#68 [FEAT] TodayQuestionViewController MVVM-C(Combine) + Adaptor Pattern 적용 (#55)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS.xcodeproj/xcshareddata/xcschemes/Plu-iOS.xcscheme
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUButton.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/TodayQuestionCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/MyAnswer/MyAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/ImageDummy.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/Interface/TodayQuestionManager.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/Interface/TodayQuestionNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/TodayQuestionAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/TodayQuestionManagerStub.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/TodayQuestionResponse.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/TodayQuestionViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/ViewController/TodayQuestionViewController.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/ViewModel/TodayQuestionViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/TodayQuestion/ViewModel/TodayQuestionViewModelImpl.swift
Labels: 👩🏻‍💻 찬미, ✨FEAT

#67 [FEAT] NicknameEditViewController MVVM-C(Combine) + Adaptor Pattern 적용(#65)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Application/AppDelegate.swift
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Global/Extention/Publisher+.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyPageCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Login/ViewModel/LoginViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/Adaptor/NicknameEditAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/Adaptor/NicknameEditNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/Model/NicknameEditInput.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/Model/NicknameEditOutput.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/NicknameEditViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/ViewController/NicknameEditViewController.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/ViewModel/NicknameEditViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/NicknameEdit/ViewModel/NicknameEditViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/Model/OnboardingInput.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/Model/OnboardingOutput.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/OnboardingInteface/NicknameCheck.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewController/OnboardingViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewModel/OnboardingViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewModel/OnboardingViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/PLUNavigationBarView.swift
Labels: 👨‍💻 의성, ✨FEAT
