Repository Team-Plu/Plu-iOS, pull requests merged in 2024-01, with the labels that each got.

#72 [FEAT] AnswerDetailViewController MVVM-C(Combine) + Adaptor Pattern 적용
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/EmpathyLarge_activated/ic_empathy_large_air_activated.imageset/ic_empathy_large_air.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/EmpathyLarge_activated/ic_empathy_large_dust_activated.imageset/ic_empathy_large_dust.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/EmpathyLarge_activated/ic_empathy_large_fire_activated.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/EmpathyLarge_activated/ic_empathy_large_fire_activated.imageset/Frame 2608660.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/EmpathyLarge_activated/ic_empathy_large_water_activated.imageset/ic_empathy_large_water.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/EmpathyLarge_inactivated/ic_empathy_large_air_inactivated.imageset/ic_empathy_large_air.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/EmpathyLarge_inactivated/ic_empathy_large_dust_inactivated.imageset/ic_empathy_large_dust.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/EmpathyLarge_inactivated/ic_empathy_large_fire_inactivated.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/EmpathyLarge_inactivated/ic_empathy_large_fire_inactivated.imageset/ic_empathy_large_fire.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/EmpathyLarge_inactivated/ic_empathy_large_water_inactivated.imageset/ic_empathy_large_water.svg
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUEverydayAnswerView.swift
  Plu-iOS/Plu-iOS/Global/Enum/ElementColor.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/Interface/AnswerDetailAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/Interface/AnswerDetailMananger.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/Interface/AnswerDetailNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/Model/AnswerDetailResponse.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/Model/EmpthyCountRequest.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/Type/AnswerDetailStub.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/Type/CountType.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewController/AnswerDetailViewController.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewModel/AnswerDetailViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewModel/AnswerDetailViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AnswerDetailCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/MyAnswer/MyAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OthersAnswerViewController.swift
Labels: 👩🏻‍💻 찬미, ✨FEAT

#75 [FEAT] ResignViewController MVVM-C(Combine) + Adaptor Pattern 적용
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyPageCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Adaptor/OthersAnswerNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Adaptor/ResignAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Adaptor/ResignNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Manager/ResignManager.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Manager/ResignManagerImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/View/ResignDescriptionView.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewController/ResignViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewModel/ResignViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewModel/ResignViewModelImpl.swift
Labels: 🧑🏻‍💻 민재, ✨FEAT

#73 [FEAT] OthersAnswerViewController MVVM-C(Combine) + Adaptor Pattern 적용 (#71)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUButton.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLULabel.swift
  Plu-iOS/Plu-iOS/Global/Combine/GesturePublisher.swift
  Plu-iOS/Plu-iOS/Global/Extention/Combine+.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyPageCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/OtherAnswerCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Adaptor/OthersAnswerAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Adaptor/OthersAnswerNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Manager/OthersAnswerManager.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Manager/OthersAnswerManagerImpl.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Model/AnswerFilter.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Model/AnswerFilterButtonType.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Model/Dummy.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OthersAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/View/AnswerFilterMenuView.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/ViewModel/OthersAnswerViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/ViewModel/OthersAnswerViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Adaptor/ResignAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Adaptor/ResignNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Manager/ResignManager.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Manager/ResignManagerImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/View/ResignDescriptionView.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewController/ResignViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewModel/ResignViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewModel/ResignViewModelImpl.swift
Labels: 🧑🏻‍💻 민재, ✨FEAT

#69 [FEAT] RecordViewController MVVM-C(Combine) + Adaptor Pattern 적용 (#66)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLUButton.swift
  Plu-iOS/Plu-iOS/DesignSystem/UIComponent/PLULabel.swift
  Plu-iOS/Plu-iOS/Global/Combine/GesturePublisher.swift
  Plu-iOS/Plu-iOS/Global/Extention/Combine+.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/AnswerDetailCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyPageCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/OtherAnswerCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/PopUpCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/RecordCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/AnswerDetailCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/OtherAnswersCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/PopUpCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/Interface/RecordCoordinator.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Adaptor/OthersAnswerAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Adaptor/OthersAnswerNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Manager/OthersAnswerManager.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Manager/OthersAnswerManagerImpl.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Model/AnswerFilter.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Model/AnswerFilterButtonType.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/Model/Dummy.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/OthersAnswerViewController.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/View/AnswerFilterMenuView.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/ViewModel/OthersAnswerViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/ViewModel/OthersAnswerViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/SelectYearAndMonthPopUp/SelectMonthPopUpViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Record/Adaptor/RecordAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/Record/Adaptor/RecordNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/Record/Manager/RecordManager.swift
  Plu-iOS/Plu-iOS/Scenes/Record/Manager/RecordManagerImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Record/Model/FilterDate.swift
  Plu-iOS/Plu-iOS/Scenes/Record/Model/RecordDiffableDataSource.swift
  Plu-iOS/Plu-iOS/Scenes/Record/Model/RecordDummy.swift
  Plu-iOS/Plu-iOS/Scenes/Record/View/QuestionView.swift
  Plu-iOS/Plu-iOS/Scenes/Record/View/RecordQuestionTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/Record/ViewController/RecordViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Record/ViewModel/RecordViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Record/ViewModel/RecordViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Adaptor/ResignAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Adaptor/ResignNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Manager/ResignManager.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/Manager/ResignManagerImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/View/ResignDescriptionView.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewController/ResignViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewModel/ResignViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewModel/ResignViewModelImpl.swift
Labels: 🧑🏻‍💻 민재, ✨FEAT

#77 [FEAT] MyPageViewController MVVM-C(Combine) + Adaptor Pattern 적용(#76)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Plu-iOS/Plu-iOS/Interface/Collections/CollectionSectionViewRegisterDequeueProtocol.swift
  Plu-iOS/Plu-iOS/Interface/Collections/CollectionViewCellRegisterDequeueProtocol.swift
  Plu-iOS/Plu-iOS/Interface/Collections/TableSectionViewRegisterDequeueProtocol.swift
  Plu-iOS/Plu-iOS/Interface/Collections/TableViewCellRegisterDequeueProtocol.swift
  Plu-iOS/Plu-iOS/Network/NetworkError.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyPageCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Adaptor/LoginAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/Login/View/TutorialCollectionViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Adaptor/MyPageAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Adaptor/MyPageAdaptorDelegate.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Adaptor/MyPageNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageAlarmTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageAppVersionTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Cell/MyPageGeneralTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Enum/MyPageSection.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Enum/MyPageUserExitType.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Enum/MypageNavigationType.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/MangerImpl/MyPageManagerStub.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MyPageUserData.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageInput.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/Model/MypageOutput.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/MyPageInerface/MyPageManager.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/MyPageInerface/MyPagePresentable.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/SectionHeader/MyPageRoundSectionHeaderView.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/View/MyPageHeaderView.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/MyPageViewController.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewModel/MyPageViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewModel/MyPageViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/Adaptor/OnboardingAdaptor.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/Adaptor/OnboardingNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/OnboardingInteface/NicknameCheck.swift
  Plu-iOS/Plu-iOS/Scenes/Onboarding/ViewModel/OnboardingViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/OthersAnswer/TableView/AnswerTableViewCell.swift
  Plu-iOS/Plu-iOS/Scenes/Record/View/RecordQuestionTableViewCell.swift
Labels: 👨‍💻 의성, ✨FEAT
