Repository Team-Plu/Plu-iOS, pull requests merged in 2024-02, with the labels that each got.

#83 [FEAT] 마이페이지 Carbon적용
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/Font/Font.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/SectionHeader/MyPageRoundSectionHeaderView.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/View/MyPageTableView.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/Items/AlarmSettingItem.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/Items/AppversionItem.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/Items/MyPageItem.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/Items/ProfileItem.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/Items/RoundHeadItem.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/Items/SpaceItem.swift
  Plu-iOS/Plu-iOS/Scenes/MyPage/ViewController/MyPageViewController.swift
Labels: 👨‍💻 의성, 🎨 UI, ♻️REFACTOR

#84 [FEAT] 소셜로그인 추가 (#82)
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Plu-iOS/Plu-iOS/Application/AppDelegate.swift
  Plu-iOS/Plu-iOS/Application/Config.swift
  Plu-iOS/Plu-iOS/Application/Configurations/Development.xcconfig
  Plu-iOS/Plu-iOS/Application/Configurations/Release.xcconfig
  Plu-iOS/Plu-iOS/Application/Info.plist
  Plu-iOS/Plu-iOS/Application/SceneDelegate.swift
  Plu-iOS/Plu-iOS/Network/NetworkError.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Manager/LoginManagerImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Model/Login.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Model/SocialLogin.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Services/AppleLoginService.swift
  Plu-iOS/Plu-iOS/Scenes/Login/Services/KakaoLoginService.swift
Labels: 🧑🏻‍💻 민재, ✨FEAT

#88 [FEAT] PopUp재사용을 위한 작업 및 회원탈퇴UI변경사항 적용
  Plu-iOS/Plu-iOS.xcodeproj/project.pbxproj
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Resign/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Resign/btn_checkbox.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Resign/btn_checkbox.imageset/btn_checkbox.svg
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Resign/btn_checkbox_fill.imageset/Contents.json
  Plu-iOS/Plu-iOS/DesignSystem/Image/Assets.xcassets/Resign/btn_checkbox_fill.imageset/btn_checkbox_fill.svg
  Plu-iOS/Plu-iOS/Global/Constant/StringConstant.swift
  Plu-iOS/Plu-iOS/Global/Extention/UILabel+.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyAnswerCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Coordinator/CoordinatorImpl/MyPageCoordinatorImpl.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/AlarmPopUp/AlarmPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/AlarmPopUp/AlarmPopUpViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/CheckPopUp/Managers/RegisterPopUpManager.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/CheckPopUp/Managers/ResignPopUpManager.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/CheckPopUp/Model/CheckPopUpText.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/CheckPopUp/Navigation/CheckPopUpNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/CheckPopUp/ViewController/CheckPopUpViewController.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/CheckPopUp/ViewModels/CheckPopUpViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/CheckPopUp/ViewModels/RegisterPopUpViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/PopUp/CheckPopUp/ViewModels/ResignPopUpViewModelImpl.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ResignNavigation.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/View/ResignDescriptionView.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewController/ResignViewController.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewModel/ResignViewModel.swift
  Plu-iOS/Plu-iOS/Scenes/Resign/ViewModel/ResignViewModelImpl.swift
Labels: 👨‍💻 의성, 🎨 UI, ✨FEAT
